name: OGM
favicon: null
layout_spectrum: 0.4170350560452789
typography_spectrum: 0.387147108791396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4350631849374622
  lightness: 0.9336329938378185
  saturation: 0.2375359353609383
  rhythmicContrast: 0.7112385388463736
purpose: []
